apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: devbranch
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            env:
              - name: NPM_CONFIG_USERCONFIG
                value: /tekton/home/npm/.npmrc
            image: uses:jenkins-x/jx3-pipeline-catalog/tasks/javascript/release.yaml@versionStream
            name: ""
            resources:
              requests:
                cpu: 0.2
                memory: 2048Mi
              limits:
                cpu: 400m
                memory: 2048Mi
            volumeMounts:
              - mountPath: /tekton/home/npm
                name: npmrc
            workingDir: /workspace/source
          steps:
            - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
              name: ""
              resources: {}
            - name: next-version
              resources: {}
            - name: jx-variables
              resources: {}
            - image: node:lts-alpine
              name: build-npm-install
              resources: {}
            - image: node:lts-alpine
              name: build-npm-test
              resources: {}
            - name: check-registry
              resources: {}
            - name: build-container-build
              resources: {}
            - name: promote-changelog
              resources: {}
            - name: promote-helm-release
              resources: {}
            - name: promote-jx-promote
              resources: {}
              script: |
                #!/usr/bin/env sh
                source .jx/variables.sh
                jx promote -b --timeout 1h --no-poll --env devbr
          volumes:
            - name: npmrc
              secret:
                optional: true
                secretName: npmrc
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
