apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            image: uses:jenkins-x/jx3-pipeline-catalog/tasks/javascript/pullrequest.yaml@versionStream
            name: ""
            resources:
              requests:
                cpu: 30m
                memory: 512Mi
              limits:
                cpu: 150m
                memory: 2048Mi
            workingDir: /workspace/source
          steps:
            - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
              name: ""
              resources: {}
            - name: jx-variables
              resources: {}
            - image: node:lts-alpine
              name: build-npm-install
              resources: {}
            - image: node:lts-alpine
              name: build-npm-test
              resources: {}
            - name: check-registry
              resources: {}
            - image: gcr.io/kaniko-project/executor:slim
              name: build-container-build
              resources: {}
              script: |
                #!/busybox/sh
                source .jx/variables.sh
                cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
                /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=${DOCKERFILE_PATH:-Dockerfile} --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
            - name: promote-jx-preview
              resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
